doc_sidebar:
  Getting Started:
    Overview: /
    Usage: usage
    Register with License-key: register-with-license-key
    Search: search
    Page-hopping: page-hopping
    Docs Browsing: docs-browsing
    Reading News: reading-news
    3rd party Recipes and Tools: 3rd-party-recipes-and-tools
  Development:
    Pagehop CLI: pagehop-cli
    Coding conventions: coding-conventions
  Develop Recipes:
    Scaffold: scaffold-recipe
    Recipe API: recipe-api
    Testing: testing-recipes
  Develop Tools:
    Scaffold: scaffold-tool
    Tool API: tool-api
    Testing: testing-tools
  Troubleshooting:
    F.A.Q.: faq

google_analytics: UA-53791435-1
fb_admins: 
twitter: pagehopapp
github: pagehop