doc_sidebar:
  How to use:
    Install: /
    Overview: overview
    Register with License-key: register-with-license-key
    Search: search
    Page-hopping: page-hopping
    Docs Browsing: docs-browsing
    Reading News: reading-news
    3rd party Recipes and Tools: 3rd-party-recipes-and-tools
  Development:
    Overview: development-overview
  Develop Recipes:
    Scaffold: scaffold-recipe
    package.json: package-json-recipe
    page-loop.js: page-loop-js
    scrape.js: scrape-js
    Testing: testing-recipes
  Develop Tools:
    Scaffold: scaffold-tool
    package.json: package-json-tool
    tool.js: tool-js
    Testing: testing-tools
  Used Software:
    Licenses: used-software
  Misc:
    Release History: releases
    F.A.Q.: faq

google_analytics: UA-53791435-1
fb_admins: 
twitter: pagehopapp
github: pagehop